### ISSUE TITLE
DI TypeError

### ISSUE THREAD

**Issue by MartinSzollos2016** [nettrine/extensions#19]
https://github.com/nettrine/extensions-atlantic18/blob/97b9927d9245ccd5b613ec7cba331e45e39f963b/src/DI/Atlantic18BehaviorExtension.php#L114

TypeError
Argument 2 passed to Nette\DI\Definitions\ServiceDefinition::addSetup() must be of the type array, object given, called in /designers/vendor/nettrine/extensions-atlantic18/src/DI/Atlantic18BehaviorExtension.php on line 11

Fix:
[$config->ipTraceable->ipValue]

**Comment by mabar** [comment]
Closed by https://github.com/nettrine/extensions-atlantic18/commit/01aced63e7f53fb67cf0c1e1c6ab037cc4052d2d
