### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by martingold** [nettrine/extensions#4]
Since namespace has changed and and readme too, it is quite challenge to figure out the right namespace to use in config when using latest stable v0.1 from composer.

The second option is to at least add notice to the readme to use 
```
gedmo: Minetro\DoctrineExtensions\DI\DoctrineExtensionsExtension
```
until new version is released.

**Comment by f3l1x** [comment]
@martingold Thanks, you're right. We'll do it as soon as possible.

**Comment by f3l1x** [comment]
Closed via https://github.com/nettrine/extensions/commit/0c0ce65cd19f8fbef5e84aeb1e2857b3278f54ff
